version: '3.2'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_srs
    ports:
    - 9090:9090
    command: 
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      corenet:
        ipv4_address: 192.0.2.4
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_srs
    privileged: true
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker
    networks:
      corenet:
        ipv4_address: 192.0.2.5
    depends_on:
    - srsenb
  srsue:
    image: srsenb
    container_name: srsue
    command: ["srsue", 
              "--log.mac_level=info",
              "--log.phy_level=debug",
              "--log.phy_lib_level=debug",
              "--rf.device_name=zmq",
              "--rf.device_args=\"fail_on_disconnect=true,tx_port=tcp://*:2001,rx_port=tcp://srsenb:2000,id=enb,base_srate=23.04e6\""]
    networks:
      rfnet:
        ipv4_address: 192.0.3.2
    cap_add:
    - CAP_SYS_NICE
    - CAP_IPC_LOCK
    - NET_ADMIN
    - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
  srsenb:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    image: srsenb
    container_name: srsenb
    cap_add:
    - CAP_SYS_NICE # set thread priority for real time thread scheduling
    - CAP_SYS_TIME
    - CAP_IPC_LOCK # for mlockall() syscall
    command: ["srsenb",
              "--enb.mme_addr=192.0.2.2",
              "--enb.gtp_bind_addr=192.0.2.3",
              "--enb.s1c_bind_addr=192.0.2.3",
              "--log.phy_level=info",
              "--expert.metrics_http_scrape_enable=true",
              "--expert.metrics_http_scrape_port=8080",
              "--rf.device_name=zmq", 
              "--rf.device_args=\"fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://srsue:2001,id=enb,base_srate=23.04e6\""]
    networks:
      corenet:
        ipv4_address: 192.0.2.3
      # hostnet: {}
      rfnet:
        ipv4_address: 192.0.3.3
    cpuset: "5"
    deploy:
      resources:
        limits:
          cpus: '2'
  srsepc:
    image: srsenb
    container_name: srsepc
    command: ["/bin/sh", "-c", 
              " echo 1 | tee /proc/sys/net/ipv4/ip_forward 1>/dev/null;
                iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
                srsepc --mme.mme_bind_addr=192.0.2.2 --spgw.gtpu_bind_addr=192.0.2.2"]
    networks:
      corenet:
        ipv4_address: 192.0.2.2
      
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24
  rfnet:
    ipam:
      driver: default
      config:
        - subnet: 192.0.3.0/24
  # hostnet:
  #   external: true
  #   name: host