scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets:
      - cadvisor:8080
- job_name: srsenb
  scrape_interval: 5s
  # scrape_timeout: 10s
  static_configs:
    - targets:
      - 192.0.2.3:8080
