scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets:
      - cadvisor:8081
- job_name: srsenb
  scrape_interval: 5s
  static_configs:
    - targets:
      - srsenb:8080
